create table if not exists public.user_profiles (
  id uuid primary key references auth.users(id) on delete cascade,
  display_name text not null default '',
  username text not null default '',
  email text not null default '',
  role text not null default 'member' check (role in ('admin', 'member')),
  status text not null default 'active' check (status in ('active', 'pending', 'disabled')),
  signup_ip inet,
  signup_user_agent text not null default '',
  signup_tracked_at timestamptz,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.support_tickets (
  id uuid primary key default gen_random_uuid(),
  ticket_number bigint generated by default as identity,
  user_id uuid not null references public.user_profiles(id) on delete cascade,
  subject text not null default '',
  category text not null default 'General' check (category in ('General', 'Donation', 'Fan Project', 'Campaign', 'Technical')),
  status text not null default 'Pending' check (status in ('Pending', 'Open', 'Closed')),
  priority text not null default 'Normal' check (priority in ('Normal', 'Urgent')),
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now())
);

create table if not exists public.support_ticket_messages (
  id uuid primary key default gen_random_uuid(),
  ticket_id uuid not null references public.support_tickets(id) on delete cascade,
  sender_user_id uuid not null references public.user_profiles(id) on delete cascade,
  sender_role text not null default 'member' check (sender_role in ('admin', 'member')),
  body text not null default '',
  created_at timestamptz not null default timezone('utc', now())
);

create index if not exists user_profiles_role_status_idx
on public.user_profiles (role, status);

create unique index if not exists user_profiles_username_unique_idx
on public.user_profiles (lower(username))
where username <> '';

create index if not exists support_tickets_user_created_idx
on public.support_tickets (user_id, created_at desc);

create index if not exists support_tickets_status_created_idx
on public.support_tickets (status, created_at desc);

create unique index if not exists support_tickets_ticket_number_idx
on public.support_tickets (ticket_number);

create index if not exists support_ticket_messages_ticket_created_idx
on public.support_ticket_messages (ticket_id, created_at asc);

alter table public.user_profiles enable row level security;
alter table public.support_tickets enable row level security;
alter table public.support_ticket_messages enable row level security;

drop trigger if exists set_user_profiles_updated_at on public.user_profiles;
create trigger set_user_profiles_updated_at
before update on public.user_profiles
for each row execute procedure public.set_updated_at();

drop trigger if exists set_support_tickets_updated_at on public.support_tickets;
create trigger set_support_tickets_updated_at
before update on public.support_tickets
for each row execute procedure public.set_updated_at();

create or replace function public.current_user_role()
returns text
language sql
security definer
set search_path = public
stable
as $$
  select coalesce(
    (select role from public.user_profiles where id = auth.uid() and status = 'active'),
    'member'
  );
$$;

create or replace function public.handle_new_user_profile()
returns trigger
language plpgsql
security definer
set search_path = public
as $$
begin
  insert into public.user_profiles (id, display_name, username, email, role, status)
  values (
    new.id,
    coalesce(new.raw_user_meta_data->>'display_name', ''),
    lower(coalesce(new.raw_user_meta_data->>'username', '')),
    coalesce(new.email, ''),
    'member',
    'active'
  )
  on conflict (id) do update
  set email = excluded.email,
      display_name = coalesce(nullif(public.user_profiles.display_name, ''), excluded.display_name),
      username = coalesce(nullif(public.user_profiles.username, ''), excluded.username);

  return new;
end;
$$;

create or replace function public.can_update_own_profile(target_id uuid, next_role text, next_status text)
returns boolean
language sql
security definer
set search_path = public
stable
as $$
  select exists (
    select 1
    from public.user_profiles
    where id = target_id
      and id = auth.uid()
      and role = next_role
      and status = next_status
  );
$$;

drop trigger if exists on_auth_user_created_create_profile on auth.users;
create trigger on_auth_user_created_create_profile
after insert on auth.users
for each row execute procedure public.handle_new_user_profile();

drop policy if exists "sbl users read own profile" on public.user_profiles;
drop policy if exists "sbl admins manage user profiles" on public.user_profiles;
drop policy if exists "sbl users create own profile" on public.user_profiles;
drop policy if exists "sbl users update own profile" on public.user_profiles;

create policy "sbl users read own profile"
on public.user_profiles for select
to authenticated
using (id = auth.uid() or public.current_user_role() = 'admin');

create policy "sbl users create own profile"
on public.user_profiles for insert
to authenticated
with check (id = auth.uid());

create policy "sbl users update own profile"
on public.user_profiles for update
to authenticated
using (id = auth.uid())
with check (public.can_update_own_profile(id, role, status));

create policy "sbl admins manage user profiles"
on public.user_profiles for update
to authenticated
using (public.current_user_role() = 'admin')
with check (public.current_user_role() = 'admin');

drop policy if exists "sbl users read own tickets" on public.support_tickets;
drop policy if exists "sbl users create own tickets" on public.support_tickets;
drop policy if exists "sbl admins update tickets" on public.support_tickets;

create policy "sbl users read own tickets"
on public.support_tickets for select
to authenticated
using (user_id = auth.uid() or public.current_user_role() = 'admin');

create policy "sbl users create own tickets"
on public.support_tickets for insert
to authenticated
with check (user_id = auth.uid());

create policy "sbl admins update tickets"
on public.support_tickets for update
to authenticated
using (public.current_user_role() = 'admin' or user_id = auth.uid())
with check (public.current_user_role() = 'admin' or user_id = auth.uid());

drop policy if exists "sbl users read own ticket messages" on public.support_ticket_messages;
drop policy if exists "sbl users create ticket messages" on public.support_ticket_messages;

create policy "sbl users read own ticket messages"
on public.support_ticket_messages for select
to authenticated
using (
  exists (
    select 1 from public.support_tickets
    where support_tickets.id = support_ticket_messages.ticket_id
    and (support_tickets.user_id = auth.uid() or public.current_user_role() = 'admin')
  )
);

create policy "sbl users create ticket messages"
on public.support_ticket_messages for insert
to authenticated
with check (
  sender_user_id = auth.uid()
  and exists (
    select 1 from public.support_tickets
    where support_tickets.id = support_ticket_messages.ticket_id
    and (support_tickets.user_id = auth.uid() or public.current_user_role() = 'admin')
  )
);
